### ISSUE TITLE
Please add support of ESModule

### ISSUE THREAD

**Issue by SaekiRaku** [rse/pure-uuid#16]
Hi, I'm trying to use this library on [Deno](https://deno.land), but `Deno` is only support `ESModuels` now, CommonJS Modules is abandoned. And even if not for `Deno`, an ESModule will be great for other projects, cause it can reduce some step to transform CommonJS Modules to ESModules.

Please add support, thanks.

**Comment by SaekiRaku** [comment]
Never mind, I have found that `Deno` has provided `uuid` module with its standard library.

**Comment by Ontopic** [comment]
I would reopen this. There is now general support in all major browsers for dynamic imports and Typescript keeps gaining ground. Types and ESModules are kinda necessary for a lib these days.

Props on the code though btw, rarely I find an utility in the NPM-ecosystem that is so "perfect"
